changed pipeline - added test, removed helm deploy; added argocd deployment

diff --git a/.github/workflows/ci-cd.yml b/.github/workflows/ci-cd.yml
--- a/.github/workflows/ci-cd.yml
+++ b/.github/workflows/ci-cd.yml
@@ -4,9 +4,13 @@ on:
   push:
     branches:
       - main
+    paths:
+      - '**'
+      - '!README.md'
+
 
 jobs:
-  build-and-push:
+  build-and-test:
     runs-on: ubuntu-latest
 
     steps:
@@ -16,32 +20,43 @@ jobs:
       - name: Set up Docker Buildx
         uses: docker/setup-buildx-action@v1
 
+      - name: Build Docker image
+        uses: docker/build-push-action@v2
+        with:
+          context: .
+          push: false
+          tags: marcinkulik/ruby-server:test
+
+      - name: Run tests and validations
+        run: |
+          # Start the container in detached mode
+          docker run -d --name test_container -p 8080:80 marcinkulik/ruby-server:test
+          
+          # Give the server a few seconds to start up
+          sleep 5
+          
+          # Send a request to the healthcheck endpoint and verify the response
+          response=$(curl -s http://localhost:8080/healthcheck)
+          if [[ "$response" == "OK" ]]; then
+            echo "Test passed!"
+          else
+            echo "Test failed!"
+            exit 1
+          fi
+          
+          # Cleanup
+          docker stop test_container
+          docker rm test_container
+
       - name: Login to DockerHub
         uses: docker/login-action@v1
         with:
           username: marcinkulik
           password: ${{ secrets.DOCKERHUB_TOKEN }}
 
-      - name: Build and push
+      - name: Push to DockerHub
         uses: docker/build-push-action@v2
         with:
           context: .
           push: true
-          tags: marcinkulik/ruby-server:latest
-
-  helm-deploy:
-    needs: build-and-push
-    runs-on: ubuntu-latest
-
-    steps:
-      - name: Checkout code
-        uses: actions/checkout@v2
-
-      - name: Set up Helm
-        uses: azure/setup-helm@v1
-        with:
-          version: 'v3.7.1' # or your desired version
-
-      - name: Deploy with Helm
-        run: |
-          helm upgrade ruby-server ./helm-chart --install
+          tags: marcinkulik/ruby-server:${{ github.run_number }}
